name: datasave
description: پلتفرم هوشمند فرم‌ساز - ایجاد و مدیریت فرم‌های آنلاین
publish_to: 'none'

# نسخه و شماره ساخت
version: 1.0.0+1

# محیط توسعه
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

# کتابخانه‌های مورد نیاز
dependencies:
  flutter:
    sdk: flutter
  
  # پشتیبانی زبان فارسی و RTL
  flutter_localizations:
    sdk: flutter
  
  # مدیریت وضعیت برنامه - از کتابخانه‌های SDK استفاده کنیم
  # provider: ^6.0.5
  
  # ارتباط با سرور و API - از داخل SDK
  # http: ^1.1.0
  
  # Material Icons
  cupertino_icons: ^1.0.2

# کتابخانه‌های توسعه
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

# تنظیمات Flutter
flutter:
  uses-material-design: true
  generate: true

  # اضافه کردن پوشه‌های assets
  assets:
    - web/fonts/
    - web/vazirmatn.css

  # تعریف فونت‌های فارسی
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: web/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: web/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: web/fonts/Vazirmatn-Light.ttf
          weight: 300
